data_source: local  # or "gcs"

sources:
  local:
    zarr_path: /Users/dennistpw/Projects/AsGARD/data/variants_combined_cohorts/
    zarr_pattern: combined_cohorts.{contig}.zarr
    metadata_path: /Users/dennistpw/Projects/AsGARD/metadata/cease_combinedmetadata.20250715.tsv
    reference_fasta_path: ~/cairn_data/reference/VectorBase-56_AdirusWRAIR2_Genome.fasta

  gcs:
    base_bucket: gs://vo_amin_release/
    zarr_path: gs://vo_amin_release/v1/snp_genotypes/all/
    metadata_path: gs://vo_amin_release/v1/metadata/samples.meta.csv
    reference_fasta_path: gs://vo_amin_release/reference/genome/aminm1/VectorBase-68_AminimusMINIMUS1_Genome.fasta

cloud:
  token: cloud

logging:
  level: INFO
